### ISSUE TITLE
Title of plugins in darkmode not visible

### ISSUE THREAD

**Issue by martin-lechene** [tomatophp/tomato#22]
Holà ! 
This is to say that the texts in the plugin section when in dark mode (found via the demo application)

![image](https://github.com/tomatophp/tomato/assets/46826871/b74dfc99-401c-4795-874e-9ebc3246fdb1)

Put a text-gray-xxx in dark mode instead of deleting it (as it already exists for light mode).

**Comment by 3x1io** [comment]
please move it to [tomato-plugins](https://github.com/tomatophp/tomato-plugins) package
