### ISSUE TITLE
UI issues in live demo (store).

### ISSUE THREAD

**Issue by MrPunyapal** [tomatophp/tomato#25]
![Screenshot_20240214-184523.png](https://github.com/tomatophp/tomato/assets/53343069/d8f57259-2a9c-4273-86fd-b5e776a9fb78)

![Screenshot_20240214-184400.png](https://github.com/tomatophp/tomato/assets/53343069/e65dddfc-1b78-4408-a922-71efbdc7cd2e)

**Comment by 3x1io** [comment]
yes the problem because of a lot of icons on the navbar we will try to fix it.

**Comment by fadymondy** [comment]
it's done now on the new release.
