### ISSUE TITLE
Can't generate crud when database is sqlite

### ISSUE THREAD

**Issue by Cybrarist** [tomatophp/tomato#28]
Hi All,

Setup: 
- Fresh install laravel 11
- installing tomatophp with tomato admin
- npm install and build
- created a model
- trying to run `php artisan tomato:generate`
- below error showing

SQLSTATE[HY000]: General error: 1 near "SHOW": syntax error (Connection: sqlite, SQL: SHOW TABLES)

**Comment by fadymondy** [comment]
just run

```bash
composer update
```

it's fixed on the new version
